### ISSUE TITLE
H2 database USER 예약어

### ISSUE THREAD

**Issue by sungyujeon** [sungyujeon/blog-advanced#6]
<h2>문제상황</h2>
SpringBoot + JPA + H2 database
프로젝트 설정 시 USER 테이블 생성 에러<br>
H2 database 2.1.214

```java
@Entity
public class User {
    // ...
}
```

```yml
spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/blog
```
위와 같이 User를 Entity 설정한 뒤 h2 database와 연결하면 
`org.hibernate.tool.schema.spi.CommandAcceptanceException: Error executing DDL "drop table if exists user CASCADE " via JDBC Statement` 에러 발생

이는 H2 database 버전에 따른 reserved word 때문에 발생하는 것
H2 2.0대 버전에서는 hibernate orm에서 예약어에 대한 문제가 있음

<h2>해결방법</h2>
1. 테이블명 변경

```java
@Entity
@Table(name = "USERS")
public class User {
    // ...
}
```
- 테이블명을 USER가 아닌 이름으로 바꾸어 해결

2. yml 설정 변경

```yml
spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/blog;NON_KEYWORDS=USER
```
